name = "db-home-planner-api"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[vars]
DB_API_BASE_URL = "https://apis.deutschebahn.com/db-api-marketplace/apis/timetables/v1"

[[d1_databases]]
binding = "db_home_planner_vrr"
database_name = "db-home-planner-vrr"
database_id = "79347905-71c6-41e8-8135-bc826396d2c8"

[[kv_namespaces]]
binding = "KV_DB_PLANNER"
id = "f1e35ba056854b999f6f6f1ef853b3d3"
preview_id = "f1e35ba056854b999f6f6f1ef853b3d3"

[dev]
port = 8787

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
