name = "db-home-planner-api"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[vars]
DB_API_BASE_URL = "https://apis.deutschebahn.com/db-api-marketplace/apis/timetables/v1"

[[d1_databases]]
binding = "DB_HOME_PLANNER_DB"
database_name = "d1_db_homeplanner"
database_id = "2ed8a449-feec-4d4e-84"

[[kv_namespaces]]
binding = "DB_HOME_PLANNER_CACHE"
id = "DB_HOME_PLANNER_CACHE"

[dev]
port = 8787

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
