name = "db-home-planner-api"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[vars]
DB_API_BASE_URL = "https://apis.deutschebahn.com/db-api-marketplace/apis/timetables/v1"

[dev]
port = 8787

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
